# Generated by Django 4.0.3 on 2022-03-15 21:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='listing_avatars', verbose_name='Avatar')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcat', to='bazar.category')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Metadata about city.', null=True, verbose_name='Metadata')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_contact', models.CharField(max_length=30, null=True, verbose_name='Preferred Contact')),
                ('metadata', models.JSONField(blank=True, help_text='Metadata about profile.', null=True, verbose_name='Metadata')),
                ('profile_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bazar.city', verbose_name='Preferred City')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('D', 'Draft'), ('O', 'Open'), ('C', 'Closed')], default='O', max_length=1, verbose_name='Status')),
                ('type', models.CharField(choices=[('P', 'Purchase'), ('S', 'Sell'), ('R', 'Request'), ('D', 'Donate')], default='D', max_length=1, verbose_name='Type')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='listing_photos', verbose_name='Photo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('viewed', models.IntegerField()),
                ('metadata', models.JSONField(blank=True, help_text='Metadata about listing.', null=True, verbose_name='Metadata')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazar.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazar.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
